name: CI

on:
  push:
  pull_request:
    branches: [ $default-branch ]
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  ubuntu:
    name: "Ubuntu"
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        otp: [25, 26, 27]
        rebar: [3.24]
    steps:
    - uses: actions/checkout@v4
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        rebar3-version: ${{matrix.rebar}}
    - name: Format check
      run: rebar3 format --verify
    - name: Tests
      run: rebar3 test

  windows:
    name: "Windows"
    runs-on: windows-latest
    strategy:
      matrix:
        otp: [25, 26, 27]
        rebar: [3.24]
    steps:
    - uses: actions/checkout@v4
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        rebar3-version: ${{matrix.rebar}}
    - name: Tests
      run: rebar3 test
